# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-18 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20170518_1802'),
        ('quiz_app', '0002_auto_20170518_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddField(
            model_name='tagtask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Task'),
        ),
    ]
