# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-18 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_auto_20170518_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtask',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Theme'),
        ),
    ]
