# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-19 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20170518_1802'),
        ('quiz_app', '0008_auto_20170519_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtask',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Theme'),
        ),
    ]
