# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-19 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_tagtask_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='count_all',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='count_true',
            field=models.FloatField(default=0),
        ),
    ]
