# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-20 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0011_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='prev_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 5, 20, 8, 37, 0, 32546, tzinfo=utc), verbose_name='Последний раз пройдено'),
            preserve_default=False,
        ),
    ]
