# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 12:51
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170511_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.upload_location, verbose_name='Изображение', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.upload_location, verbose_name='Изображение', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
