# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='', max_length=100, verbose_name='Тип раздела'),
            preserve_default=False,
        ),
    ]
