# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-12 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170512_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='updated',
        ),
    ]
