# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-13 10:51
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170512_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=350, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location, verbose_name='Изображение')),
                ('content', models.TextField(null=True, verbose_name='Содержание')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-title']},
        ),
        migrations.AddField(
            model_name='help',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Theme'),
        ),
    ]
