# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 11:06
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20170513_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location, verbose_name='Изображение'),
        ),
    ]
