# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='extra_title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Расширенное название'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_title',
            field=models.CharField(max_length=350, verbose_name='Тема'),
        ),
    ]
