# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20170514_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='inner_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Unit'),
        ),
    ]
