# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20170516_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Word'),
        ),
    ]
