# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_task_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Task')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Word')),
            ],
        ),
    ]
