# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_taskword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='word',
        ),
    ]
