# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_remove_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='kanji',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Слово (кандзи)'),
        ),
        migrations.AlterField(
            model_name='word',
            name='onyomi',
            field=models.CharField(blank=True, max_length=230, null=True, verbose_name='Верхнее чтение'),
        ),
    ]
