# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20170517_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Tag')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Theme')),
            ],
        ),
    ]
