# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-17 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_tagtheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagword',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagword',
            name='word',
        ),
        migrations.DeleteModel(
            name='TagWord',
        ),
    ]
