# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-17 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20170517_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Theme')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='theme',
        ),
        migrations.AddField(
            model_name='wordtheme',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Word'),
        ),
    ]
