# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20170517_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Theme'),
        ),
    ]
