# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-17 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20170517_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpimage',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Название'),
        ),
    ]
