# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20170518_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='num',
        ),
        migrations.AddField(
            model_name='task',
            name='answer_text1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ответ 1'),
        ),
        migrations.AddField(
            model_name='task',
            name='answer_text2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ответ 2'),
        ),
        migrations.AddField(
            model_name='task',
            name='answer_text3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ответ 3'),
        ),
        migrations.AddField(
            model_name='task',
            name='answer_text4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ответ 4'),
        ),
        migrations.AddField(
            model_name='task',
            name='num1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество ответов'),
        ),
        migrations.AddField(
            model_name='task',
            name='num2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество ответов'),
        ),
        migrations.AddField(
            model_name='task',
            name='num3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество ответов'),
        ),
        migrations.AddField(
            model_name='task',
            name='num4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество ответов'),
        ),
        migrations.AddField(
            model_name='task',
            name='ok1',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ok2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ok3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ok4',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
